version: "3.8"
services:
  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
      # volumes:
      # - /somedirectory:/data/db  # you need to mondify this
    ports:
      - 27017:27017
    restart: unless-stopped
    
  django:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017  